version: '3.3'
services:
    chatgpt-proxy:
        image: 24802117/chatgpt_api:latest
        container_name: chatgpt-api-v2
        ports:
            - '9090:9090'
        environment:
          api: http://xxxx/token?key=xxxx
          login_api: http://xxxx/login_token?key=xxxx
          3-5-ArkoseToken: http://xxxxx/token?key=xxx
          arkoselabs: 1
          PROXY: http://127.0.0.1:4000
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock:ro
